
# notice that there is no tasks header

- name: install python bindings for SELinux
  yum: name={{item}} state=present
  with_items:
   - libselinux-python
   - libsemanage-python

- name: test to see if SELinux is renning
  command: getenforce
  register: sestatus
  changed_when: false

